package wang.fly.com.yunhealth.DataBasePackage;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import wang.fly.com.yunhealth.R;

import static wang.fly.com.yunhealth.R.drawable.check;

/**
 * Created by 82661 on 2016/11/17.
 */

public class MyDataBase extends SQLiteOpenHelper {
    private static final String TAG = "MyDataBase";
    public static final String CREATE_REPORT_MENU = "" +
            "create table report_menu (" +
            "id integer primary key autoincrement," +
            "content text unique," +
            "image integer," +
            "type integer," +
            "checked integer)";
    private Context context;

    public MyDataBase(Context context,
                      String name,
                      SQLiteDatabase.CursorFactory factory,
                      int version) {
        super(context, name, factory, version);
        this.context = context;
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(CREATE_REPORT_MENU);
        Log.d(TAG, "onCreate: database");
    }

    public void addData(SQLiteDatabase db) {
        //检验单
        ContentValues values = new ContentValues();
        values.put("content", "血常规");
        values.put("image", R.drawable.jcd_ic_rb);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "血生化全套");
        values.put("image", R.drawable.jcd_ic_bb);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "他克莫司浓度");
        values.put("image", R.drawable.jcd_ic_fk);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "环孢素浓度");
        values.put("image", R.drawable.jcd_ic_csa);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "雷帕霉素浓度");
        values.put("image", R.drawable.jcd_ic_rapa);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "尿常规");
        values.put("image", R.drawable.jcd_ic_rt);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "群体反应抗体(PRA)");
        values.put("image", R.drawable.jcd_ic_grad1);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "超敏C反应蛋白");
        values.put("image", R.drawable.jcd_ic_acpd);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "凝血功能");
        values.put("image", R.drawable.jcd_ic_csa);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "血气分析");
        values.put("image", R.drawable.jcd_ic_bga);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肿瘤标志物");
        values.put("image", R.drawable.jcd_ic_tm);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肝炎系列");
        values.put("image", R.drawable.jcd_ic_hbs);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "血型");
        values.put("image", R.drawable.jcd_ic_bt);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "粪便常规");
        values.put("image", R.drawable.jcd_ic_fr);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "甲状旁腺激素");
        values.put("image", R.drawable.jcd_ic_pth);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "多瘤病毒");
        values.put("image", R.drawable.jcd_ic_bkv);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "乙肝病毒");
        values.put("image", R.drawable.jcd_ic_hbv_dna);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "霉芬酸");
        values.put("image", R.drawable.jcd_ic_mpa);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肾功能");
        values.put("image", R.drawable.jcd_ic_shengongneng);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肝功能");
        values.put("image", R.drawable.jcd_ic_gangongneng);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "血脂");
        values.put("image", R.drawable.jcd_ic_xuezhi);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "糖化血红蛋白");
        values.put("image", R.drawable.ft_ic_tanghuaxuehong);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "B2微球蛋白");
        values.put("image", R.drawable.ft_ic_weiqiudanbai);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "转铁蛋白+前白蛋白测定");
        values.put("image", R.drawable.ft_ic_zhuantiedaibai);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "铁三项");
        values.put("image", R.drawable.ft_ic_tiesanxiang);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "常规四项");
        values.put("image", R.drawable.ft_ic_changgui);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "尿蛋白、尿素、肌酐测定");
        values.put("image", R.drawable.ft_ic_niaodanbai);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "腹水常规检查");
        values.put("image", R.drawable.ft_ic_fushui);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "腹透液Cr、BuN、pro");
        values.put("image", R.drawable.ft_ic_futouye);
        values.put("type", 1);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        //检查单
        values.put("content", "心电图");
        values.put("image", R.drawable.jdc_icon_ecg);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "心超");
        values.put("image", R.drawable.icon_xinchao);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "颈部血管B超");
        values.put("image", R.drawable.jcd_ic_jingbuxueguanbchao);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "左上肢动脉超声");
        values.put("image", R.drawable.icon_zuoshangzhidongmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "左上肢静脉超声");
        values.put("image", R.drawable.icon_zuoshangzhijingmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "右上肢动脉超声");
        values.put("image", R.drawable.icon_youshangzhidongmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "右上肢静脉超声");
        values.put("image", R.drawable.icon_youshangzhijingmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "左下肢动脉超声");
        values.put("image", R.drawable.icon_zuoxiazhidongmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "左下肢静脉超声");
        values.put("image", R.drawable.icon_zuoxiazhijingmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "右下肢动脉超声");
        values.put("image", R.drawable.icon_youxiazhidongmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "左下肢静脉超声");
        values.put("image", R.drawable.icon_youxiazhijingmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "胸片");
        values.put("image", R.drawable.icon_xiongpian);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肺部CT");
        values.put("image", R.drawable.icon_feipian);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肝胆脾胰超声");
        values.put("image", R.drawable.icon_gandanpiyi);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "泌尿系B超");
        values.put("image", R.drawable.jcd_ic_miniaoxibchao);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "移植肾超声");
        values.put("image", R.drawable.jcd_ic_ultrasound);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "胸水超声");
        values.put("image", R.drawable.icon_xiongshuichaosheng);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "腹水超声");
        values.put("image", R.drawable.icon_fubuchaosheng);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "头部CT");
        values.put("image", R.drawable.icon_toulu);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "头颅MRI");
        values.put("image", R.drawable.icon_toulumir);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "颈部及腋下淋巴结超声");
        values.put("image", R.drawable.icon_jinbujiyexialinbajie);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "腹股沟淋巴结超声");
        values.put("image", R.drawable.icon_fugugoulinbajie);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肾动脉CT");
        values.put("image", R.drawable.icon_shendongmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "肾静脉CT");
        values.put("image", R.drawable.icon_shenjingmai);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "磁共振泌尿系水成像检查");
        values.put("image", R.drawable.icon_cigongzhenminiao);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
        values.put("content", "CT尿路造影");
        values.put("image", R.drawable.icon_ctniaoluzaoying);
        values.put("type", 2);
        values.put("checked", 0);
        db.insert("report_menu", null, values);
        values.clear();
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
